In [2]:
import numpy as np
import pandas as pd

In [3]:
l=[[2,6],
  [3,4],
  [3,8],
  [4,7],
  [6,2],
  [6,4],
  [7,3],
  [7,4],
  [8,5],
  [7,6]]

In [11]:
ans=np.zeros((10,10))
for c1 in range(0,10):
    for c2 in range(c1+1,10):
            cost=0
            for i in l:
                d1=abs(i[0]-l[c1][0])+abs(i[1]-l[c1][1])
                d2=abs(i[0]-l[c2][0])+abs(i[1]-l[c2][1])
                cost=cost+min(d1,d2)
            ans[c1][c2]=cost
            ans[c2][c1]=cost
print("Min Cost if i,j are chosen as cluster centroids:")
print(ans)

Min Cost if i,j are chosen as cluster centroids:
[[ 0. 34. 46. 40. 26. 20. 20. 18. 24. 24.]
 [34.  0. 34. 32. 28. 22. 22. 20. 26. 26.]
 [46. 34.  0. 42. 26. 19. 20. 18. 24. 24.]
 [40. 32. 42.  0. 25. 19. 20. 18. 24. 24.]
 [26. 28. 26. 25.  0. 30. 38. 31. 34. 28.]
 [20. 22. 19. 19. 30.  0. 30. 28. 28. 25.]
 [20. 22. 20. 20. 38. 30.  0. 32. 33. 27.]
 [18. 20. 18. 18. 31. 28. 32.  0. 32. 26.]
 [24. 26. 24. 24. 34. 28. 33. 32.  0. 34.]
 [24. 26. 24. 24. 28. 25. 27. 26. 34.  0.]]
